//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inFizYon.Ontology
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class inMF
    {
        //public inMF()
        //{
        //    this.specSection = new HashSet<specSection>();
        //}
        [Key]
        [ForeignKey("PhraseRepository")]
        //[DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int SectionID { get; set; }

        [Display(Name = "MasterFormat Section")]
        public string SecNr { get; set; }
        public enum SecSource : byte //may not be necessary - data model changed to a recursive layout.
        {   
            M = 0, //MasterFormat'12
            O = 1, //OmniClass T22
            C = 2, //Custom
            H = 3  //Hybrid
        }

        public virtual Phrase PhraseRepository { get; set; }
        //public virtual ICollection<specSection> secTxts { get; set; }
    }
}
